version: 2.0

jobs:
  build:
    # Build default image (STM32MP157C-DK2)
    machine: true
    working_directory: ~/project
    resource_class: large
    steps:
      - checkout
      - run: make build_image_dk2

workflows:
  version: 2
  build_all:
    jobs:
      - build
