version: 2.0

jobs:
  build_image_dk2:
    # Build default image (STM32MP157C-DK2)
    machine: true
    working_directory: ~/project
    resource_class: large
    steps:
      - checkout
      - run: make build_image_dk2

  build_image_bytesatwork:
    # Build bytesatwork image
    machine: true
    working_directory: ~/project
    resource_class: large
    steps:
      - checkout
      - run: make build_image_bytesatwork

workflows:
  version: 2
  build_all:
    jobs:
      - build_image_dk2
      - build_image_bytesatwork
